### ISSUE TITLE
 Cannot read properties of undefined (reading 'first')

### ISSUE THREAD

**Issue by aravindaftd** [andrechristikan/ack-nestjs-boilerplate-kafka#278]
Hi All,
I'm getting a error when i'm listening to a kafka topic each time.

ERROR [RpcExceptionsHandler] Cannot read properties of undefined (reading 'first')

ERROR [Runner] Error when calling eachMessage {"timestamp":"2022-12-30T19:26:59.954Z","logger":"kafkajs","topic":"TOPIC_NAME","partition":0,"offset":"49","error":{"status":"error","message":"Internal server error"}}

**Comment by aravindaftd** [comment]
This starts to works once after allow auto topic creation enabled from configs. however in my project i had removed the producer scenarios and just going with only the consumer at the moment

**Comment by andrechristikan** [comment]
I investigate the issue.

**Comment by andrechristikan** [comment]
After i investigated it. That because you do not have the topics.

For information
This repo already provide for do migrate topic (seed topic / create topic). You can run 
```bash
yarn create:kafka-topics
```

Or if you want to create topic with automatically. 

> src/configs/kafka.config.ts

- Repo version `< 3.2.0`
You can change the `allowAutoTopicCreation` to `true`, both with `producer` and `consumer`

- Repo version `>= 3.2.0`
You can change the `allowAutoTopicCreation` to `true` at root level
